services:
  - type: web
    name: kaiyuanshe-server
    plan: free
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 14.19.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kaiyuanshe-data
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: kaiyuanshe-data
    plan: free
