services:
  - type: web
    name: kaiyuanshe-server
    plan: free
    env: node
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 14.19.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kaiyuanshe-data
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: STORAGE_URL
        value: https://ows.blob.core.chinacloudapi.cn
      - key: STORAGE_ACCOUNT
        value: ows
      - key: STORAGE_CONTAINER_NAME
        value: files

databases:
  - name: kaiyuanshe-data
    plan: free
