name: Deploy Server
on:
  push:
    branches:
      - master
jobs:
  SSH:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Clean
        run: |
          rm -rf .git/ .gitignore .github/ .editorconfig .eslint*
      - name: Transport
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: ${{ secrets.PATH }}
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.KEY }}
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.KEY }}
          command: |
            cd ${{ secrets.PATH }}
            echo BASE_URL=${{ secrets.BASE_URL }} > .env
            echo STORAGE_ACCOUNT_KEY=${{ secrets.STORAGE_ACCOUNT_KEY }} >> .env
            echo '${{ secrets.KEY }}' | sudo -S ~/.local/bin/docker-compose down
            echo '${{ secrets.KEY }}' | sudo -S ~/.local/bin/docker-compose up -d
